create sequence hibernate_sequence start 1 increment 1;


create table _user (
                       salary float(53),
                       id bigint generated by default as identity,
                       manager_id bigint,
                       first_name varchar(20) not null,
                       last_name varchar(20) not null,
                       login varchar(20) not null unique,
                       email varchar(30) not null unique,
                       position varchar(40) not null,
                       password varchar(60) not null,
                       role varchar(255) not null check (role in ('USER','MANAGER','ADMIN')),
                       primary key (id)
);

create table bonus (
                       bonus_amount float(53),
                       calculation_period date not null,
                       critical_priority_count integer not null,
                       efficiency_rate float(53),
                       medium_priority_count integer not null,
                       normal_priority_count integer not null,
                       total_tasks_completed integer not null,
                       awarded_at timestamp(6),
                       employee_id bigint not null,
                       id bigint generated by default as identity,
                       manager_id bigint not null,
                       primary key (id)
);

create table task (
                      completed_date date,
                      due_date date,
                      start_date date,
                      assignee_id bigint,
                      author_id bigint not null,
                      created_at timestamp(6),
                      id bigint generated by default as identity,
                      updated_at timestamp(6),
                      title varchar(50) not null,
                      description TEXT,
                      priority varchar(255) not null check (priority in ('EASY','MEDIUM','CRITICAL')),
                      status varchar(255) not null check (status in ('OPEN','IN_PROGRESS','COMPLETED')),
                      primary key (id)
);

alter table if exists _user add constraint FKawn6stcmspiskwrsh3np1m88b foreign key (manager_id) references _user;
alter table if exists bonus add constraint FK3wpmnp5yr57krinqoys1l0kxb foreign key (employee_id) references _user;
alter table if exists bonus add constraint FK1ben2xwlcamfl90vl7j7952ta foreign key (manager_id) references _user;
alter table if exists task add constraint FKnepwr11ituhk7gwgsmwr3p54n foreign key (assignee_id) references _user;
alter table if exists task add constraint FKlqd6ftj7rha904bn1lrg7wx2n foreign key (author_id) references _user;
